#Nombre de la API
spring.application.name=movies-api
#Ubicación y nombre de la base de datos (DB) 
spring.datasource.url=jdbc:h2:mem:moviesdatabase
#Driver (traductor JDBC y lengua DB, H2)
spring.datasource.driver-class-name=org.h2.Driver

#Credenciales de acceso a DB (dejo vacía por ahora)
spring.datasource.username=sa
spring.datasource.password=

#Consola web activa
spring.h2.console.enabled=true
